### ISSUE TITLE
Checklist for release

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/CaosDB.jl#3]
Here are some requirements that we need to fulfill before this is released as a package someone can use:

- [x] Quick get started guide in the README that points to the official CaosDB wiki
- [ ] Unit tests on both Windows and Linux
- [ ] Communication tests (with e.g. the dummy server) for both windows and linux
- [ ] Julia-package related: Make it into a proper package, resolve dependencies, export necessary names, etc.
- [x] Installation: Make sure package installs in both Linux and Windows and the C library is usable everywhere. (if the C library is necessary).

**Comment by salexan2001** [comment]
Currently the testing server "playground.indiscale.com" is not running. I think, in the long run, it makes sense to use a docker container as the test server.
